using System;

public enum GEnum4
{
	[GAttribute70("drone_formation_default")]
	Default,
	[GAttribute70("drone_formation_f-01-tu")]
	Turtle,
	[GAttribute70("drone_formation_f-02-ar")]
	Arrow,
	[GAttribute70("drone_formation_f-04-st")]
	Star,
	[GAttribute70("drone_formation_f-06-da")]
	DoubleArrow,
	[GAttribute70("drone_formation_f-05-pi")]
	Pincer,
	[GAttribute70("drone_formation_f-07-di")]
	Diamond,
	[GAttribute70("drone_formation_f-08-ch")]
	Chevron,
	[GAttribute70("drone_formation_f-09-mo")]
	Moth,
	[GAttribute70("drone_formation_f-11-he")]
	Heart,
	[GAttribute70("drone_formation_f-10-cr")]
	Crab,
	[GAttribute70("drone_formation_f-12-ba")]
	Barrage,
	[GAttribute70("drone_formation_f-3d-dm")]
	Dome,
	[GAttribute70("drone_formation_f-3d-dr")]
	Drill,
	[GAttribute70("drone_formation_f-3d-rg")]
	Ring,
	[GAttribute70("drone_formation_f-3d-vt")]
	Veteran,
	[GAttribute70("drone_formation_f-3d-wl")]
	Wheel,
	[GAttribute70("drone_formation_f-3d-wv")]
	Wave,
	[GAttribute70("drone_formation_f-3d-x")]
	X,
	[GAttribute70("drone_formation_f-13-bt")]
	Bat
}
