using System;

namespace DarkorbitAPI.Packets.Static
{
	public enum ResourceType
	{
		BIFENON = 19,
		TARNOM = 25,
		PROMERIUM = 6,
		OPITITE = 26,
		DUOTHRIN = 14,
		MUCOSUM = 9,
		HYBRID_ALLOY = 21,
		XENOMIT = 3,
		QUADROTHRIN = 16,
		PROMETIUM = 0,
		DURANIUM = 5,
		SCRAPIUM = 11,
		RINUSK = 22,
		F_1 = 13,
		BLACKLIGHT_TRACE = 23,
		MINDFIRE_CEREBRUM,
		BOLTRUM = 10,
		PROMETID = 4,
		ENDURIUM = 1,
		TERBIUM,
		SEPROM = 7,
		TETRATHRIN = 18,
		PALLADIUM = 8,
		TRITTOTHRIN = 15,
		PRISMATIUM = 12,
		INDOCTRINEOIL = 20,
		KYHALON = 17
	}
}
